name: TF Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  terraform_apply:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN_SECRET }}
        role-session-name: github_actions_terraform_cred
        aws-region: us-east-1

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.4

    - name: Terraform Init
      working-directory: ./tfresources
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./tfresources
      id: plan
      if: github.event_name == 'push'
      run: terraform plan -no-color
      continue-on-error: true
    
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    
    - name: Terraform Apply
      working-directory: ./tfresources
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve